name: Retardify commit message

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Git setup
      run: |
        git config user.email "julio.arruda@outlook.com"
        git config user.name "Julio Arruda"
    - name: Retardify commit message
      run: |
        chmod +x ./asciiArt.py && chmod +x ./retardify.py
        ./asciiArt.py
        message=$(git log -1 --pretty=%B)
        retardifiedMessage=$(./retardify.py "${message}")
        git commit --amend -m "${retardifiedMessage}"
    - name: Push the new message
      run: |
        branchName=$(git branch | grep '*' | tr -d '* ')
        git pull --allow-unrelated-histories
        git push origin ${branchName}
